### ISSUE TITLE
android的kotlin的添加安全图片重新编译还是出错

### ISSUE THREAD

**Issue by sparksisnotspark** [FlutterTaoBaoKe/flutter_alibc#18]
```
[com.alibaba.baichuan.trade.common.adapter.security.c.a:70] AlibcSecurity init 
    ErrorCode = 123
    com.alibaba.wireless.security.open.SecException: 
        at com.taobao.wireless.security.adapter.JNICLibrary.doCommandNative(Native Method)
        at com.alibaba.wireless.security.mainplugin.a.doCommand(Unknown Source:0)
        at com.alibaba.wireless.security.mainplugin.SecurityGuardMainPlugin.onPluginLoaded(Unknown Source:147)
        at com.alibaba.wireless.security.framework.d.a(Unknown Source:1230)
        at com.alibaba.wireless.security.framework.d.d(Unknown Source:50)
        at com.alibaba.wireless.security.framework.d.getPluginInfo(Unknown Source:3)
        at com.alibaba.wireless.security.open.initialize.b.a(Unknown Source:29)
        at com.alibaba.wireless.security.open.initialize.a.loadLibrarySync(Unknown Source:5)
        at com.alibaba.wireless.security.open.initialize.a.initialize(Unknown Source:0)
        at com.alibaba.baichuan.trade.common.adapter.security.c.a(Unknown Source:15)
        at com.alibaba.baichuan.trade.common.adapter.security.AlibcSecurityGuard.init(Unknown Source:54)
        at com.alibaba.baichuan.trade.common.AlibcTradeCommon.init(Unknown Source:31)
        at com.alibaba.baichuan.trade.biz.AlibcTradeBiz.init(Unknown Source:15)
        at com.alibaba.baichuan.android.trade.AlibcTradeSDK.b(Unknown Source:3)
        at com.alibaba.baichuan.android.trade.AlibcTradeSDK.a(Unknown Source:0)
        at com.alibaba.baichuan.android.trade.AlibcTradeSDK$1.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
添加的安全图片，还是出这个错误，谁知道是啥问题么

**Comment by sparksisnotspark** [comment]
这个123的错误代码也不晓得是个啥

**Comment by karedem** [comment]
Android版本百川电商SDK问题： 
1、H5授权登录错误：406 服务竟然出错了
SDK升级至4.0版本时，需要重新获取下V5的安全图片，请认真阅读下升级指南和4.0开发文档。

 

2、没有手淘，H5加载优惠券页面，显示宝贝不见了
目前该类页面只支持唤端 如果没有安装手淘会跳转引导下载页（设置失败模式为H5会导致错误页面） 后续会逐步支持应用内h5打开 

 

3、初始化203错误
1.打包后报的，shrinkResources false//设置为false，true的话，安全图片可能会被删除

2.在AS中报错，有可能是instant run导致

关于删除安全图片的问题, 建议在项目中写一个不可见的view , 引用一下yw_1222.jpg ,这样在优化资源的时候，发现图片被引用，就不会被删除。

 

4、通过电商SDK唤起手淘后，没有显示返回小把手
请认真阅读下4.0开发文档，需要设置backURL

 

5、初始化失败 AlibcSecurity init ErrorCode = 123
1.请先对照下4.0版本开发文档，看依赖是否为最新的

2.暂时将Android studio降低到3.5以下的版本试试

 

6、初始化失败 AlibcSecurity init  ErrorCode = 202
安全图片的问题，请确保获取安全图片的APK包名、签名文件与使用的项目一致

https://baichuan.taobao.com/docs/doc.htm?spm=a3c0d.7629140.0.0.6be7be48Cmvvdk&treeId=129&articleId=118171&docType=1

**Comment by karedem** [comment]
初始化失败 请查阅文档
