### ISSUE TITLE
打开闪退，couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by MX8CLUB** [FlutterTaoBaoKe/flutter_alibc#78]
```
/AndroidRuntime(24584): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.XXXXX-1/base.apk"],nativeLibraryDirectories=[/data/app/com.XXXXX-1/lib/arm, /data/app/com.XXXXX-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
E/AndroidRuntime(24584): 	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
E/AndroidRuntime(24584): 	at java.lang.System.loadLibrary(System.java:1562)
E/AndroidRuntime(24584): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:129)
E/AndroidRuntime(24584): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:123)
```
去掉依赖就正常，模拟器运行

**Comment by XingXiaoWu** [comment]
@karedem

**Comment by karedem** [comment]
模拟器一般需要支持x86架构的so flutter编译时默认不带x86  
不属于插件问题  需要支持模拟器请自行在项目配置

**Comment by karedem** [comment]
这是运行example在android模拟器上  并没有报错
![image](https://user-images.githubusercontent.com/22335363/108968908-59f3a100-76bc-11eb-9108-e0a6fbb237f5.png)
